import "./globals.css";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/shared/Footer";
import PatientWrapper from "@/components/patient/PatientWrapper";
import FinalLayout from "@/components/shared/FinalLayout";
import ClientReduxProvider from "@/components/shared/ClientReduxProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <ClientReduxProvider>
          <FinalLayout>
            {children}
            <Toaster
              position="top-right"
              toastOptions={{
                style: {
                  background: "#fff",
                  color: "#333",
                  borderRadius: "10px",
                  padding: "12px 16px",
                  boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
                },
                success: {
                  style: {
                    background: "#e6f4ff",
                    border: "1px solid #1195FF",
                    color: "#1195FF",
                    fontWeight: "500",
                  },
                  iconTheme: {
                    primary: "#1195FF",
                    secondary: "#fff",
                  },
                },
                error: {
                  style: {
                    background: "#ffe6e6",
                    border: "1px solid #ff4d4f",
                    color: "#ff4d4f",
                    fontWeight: "500",
                  },
                  iconTheme: {
                    primary: "#ff4d4f",
                    secondary: "#fff",
                  },
                },
              }}
            />
          </FinalLayout>
        </ClientReduxProvider>
      </body>
    </html>
  );
}
