import ClientLayout from "./ClientLayout";
import "./globals.css";

export const metadata = {
  title: "Doctors Online",
  description: "Generated by Next.js",
  icons: {
    icon: "/doctorsonlineLogo.jpg", // favicon (tab icon)
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
